description: "cifar conv small with jp"
adaptive_alpha: False
adaptive_basis: False
adaptive_eps: False
adv_attack: True
alpha: 0.06
check_sound: False
conv: True
dataset: cifar
dilation_new_base: 30
domain: chzono
double: True
eps: 0.00784313725
explicit: -1
fixed_point_init: True
hidden: 8
iters: 500
joint_projection: True
kernel_x: 6
log: logs/cifar_conv_m1_c8_k6_s3_e2_pr_06_sfwbw_aa_postd30_jp1_os0.txt
m: 20
max_eps: 0.03137254901960784
no_box_term: False
number_verifications: 100
optimize_slopes: 0
path: models/cifar_tiny_mon_conv_c8_k6_s3_m20.0.pt
peaceman_rachford: True
post_proj_dil: 30
pre_proj_dil: 3
proj_start: 10
require_contained: False
stride_x: 3
switch_to_fwbw: 0.033
verbose: False
widening_iter: 2