description: "HCAS global"
adaptive_alpha: False
adaptive_basis: False
adaptive_eps: False
adv_attack: False
alpha: 0.037
check_sound: False
conv: False
dataset: HCAS_p0_t0
dilation_new_base: 20
domain: chzono
double: True
eps: 0.04
explicit: -1
fixed_point_init: True
hidden: 100
iters: 300
joint_projection: True
kernel_x: 6
log: logs/HCAS_p0_t0_100_m20_pr_035_wid-1_jp1_slice_global.txt
m: 20
max_eps: 0.03137254901960784
no_box_term: False
number_verifications: 100
optimize_slopes: 0
path: models/HCAS_p0_t0_mon_h100_m20.0.pt
peaceman_rachford: True
post_proj_dil: 20
pre_proj_dil: 10
proj_start: 10
require_contained: False
stride_x: 3
switch_to_fwbw: 0.033
verbose: False
widening_iter: -1
verify_range: True
range_x: [-10000., 30000.]
range_y: [-10000., 30000.]
range_psi: [-180., 0.]
range_depth: 2
