description: "mnist h 200 m 20"
adaptive_alpha: True
adaptive_basis: False
adaptive_eps: False
adv_attack: True
alpha: 0.06
check_sound: False
conv: False
dataset: mnist
dilation_new_base: 30
domain: chzono
double: True
eps: 0.05
explicit: -1
fixed_point_init: True
hidden: 200
iters: 500
joint_projection: True
kernel_x: 6
log: logs/mnist_200_m20_e05_pr_1_sfwbw_aa_wid-1_jp1_os2.txt
m: 20
max_eps: 0.03137254901960784
no_box_term: False
number_verifications: 100
optimize_slopes: 2
path: models/mnist_mon_h200_m20.0.pt
peaceman_rachford: True
post_proj_dil: 50
pre_proj_dil: 5
proj_start: 10
require_contained: False
stride_x: 3
switch_to_fwbw: 0.033
verbose: False
widening_iter: -1