description: "matlab only PR"
adaptive_alpha: False
adaptive_basis: False
adaptive_eps: False
adv_attack: False
alpha: 0.04
check_sound: False
conv: False
dataset: mnist
dilation_new_base: 30
domain: chzono
double: True
eps: 0.05
explicit: -1
fixed_point_init: True
hidden: 40
iters: 500
joint_projection: True
kernel_x: 6
log: logs/mnist_matlab_e05_pr_02_wid-1_jp1_os2.txt
m: 20
max_eps: 0.03137254901960784
no_box_term: False
number_verifications: 100
optimize_slopes: 2
path: mat_models/deq_MNIST_SingleFcNet_m=20.mat
peaceman_rachford: True
post_proj_dil: 50
pre_proj_dil: 3
proj_start: 3
require_contained: False
stride_x: 3
switch_to_fwbw: False
verbose: False
widening_iter: -1
verify_range: False
range_x: [0., 0.]
range_y: [0., 0.]
range_psi: [0., 0.]
range_depth: 0