description: "mnist conv small"
adaptive_alpha: True
adaptive_basis: False
adaptive_eps: False
adv_attack: True
alpha: 0.1
check_sound: False
conv: True
dataset: mnist
dilation_new_base: 30
domain: chzono
double: True
eps: 0.05
explicit: -1
fixed_point_init: True
hidden: 8
iters: 500
joint_projection: True
kernel_x: 6
log: logs/mnist_conv_c8_k6_s3_e05_pr_1_sfwbw_aa_postd30_jp1_os2.txt
m: 20
max_eps: 0.03137254901960784
no_box_term: False
number_verifications: 100
optimize_slopes: 2
path: models/mnist_sm_mon_conv_c8_k6_s3_m20.0.pt
peaceman_rachford: True
post_proj_dil: 30
pre_proj_dil: 5
proj_start: 5
require_contained: False
stride_x: 3
switch_to_fwbw: 0.033
verbose: False
widening_iter: 0